name: App Center

trigger: none

variables:
- group: app_center
- name: app_center_job_name
  value: 'appcenter'
- name: artifact_name
  value: 'my-app'

jobs:
  - template: templates/app-center/build.yml    
    parameters:
      job_name: '${{ variables.app_center_job_name }}'
      owner: '$(APP_CENTER_ORG)'
      app: '$(APP_CENTER_APP)'
      branch: '$(Build.SourceBranchName)'
      artifact_name: '$(artifact_name)'
      token: '$(APP_CENTER_TOKEN)'

  - job: distribute_intune
    displayName: 'Distribute'
    dependsOn: ['${{ variables.app_center_job_name }}']
    variables:
      apk: $[ dependencies.${{ variables.app_center_job_name }}.outputs['build.apk'] ]
      store: 'My Company Store'
    steps:
      - download: current        
        artifact: $(artifact_name)
        displayName: 'Download APK'

      - task: AppCenterDistribute@3
        displayName: 'Distribute to Intune'
        inputs:
          serverEndpoint: 
          appSlug: '$(APP_CENTER_ORG)/$(APP_CENTER_APP)'
          appFile: '$(Pipeline.Workspace)\$(artifact_name)\$(apk)'
          symbolsOption: 'Android'
          releaseNotesOption: 'input'
          releaseNotesInput: 'New Release'
          destinationType: 'store'
          destinationStoreId: $(store)