name: App Center

trigger: none

variables:
- group: app_center

jobs:
  - template: templates/app-center/build.yml    
    parameters:
      owner: '$(APP_CENTER_ORG)'
      app: '$(APP_CENTER_APP)'
      branch: '$(Build.SourceBranchName)'
      artifact_name: 'my-app-apk'
      token: '$(APP_CENTER_TOKEN)'

      