parameters:
- name: job_name
  type: string
- name: owner
  type: string
- name: app
  type: string
- name: branch
  type: string
- name: artifact_name
  type: string
- name: token
  type: string

jobs:
- job: ${{ parameters.job_name }}
  displayName: 'Build'
  pool:
    vmImage: ubuntu-latest
  variables:
    build_output: '$(Agent.TempDirectory)/app-center'
  
  steps:
  - bash: |
      npm install -g appcenter-cli
    displayName: 'Install App Center CLI'
  - bash: |
      chmod +x .azure/templates/app-center/scripts/entrypoint.sh
      .azure/templates/app-center/scripts/entrypoint.sh '${{ parameters.owner }}' '${{ parameters.app }}' '${{ parameters.branch }}' '${{ parameters.artifact_name }}' '${{ variables.build_output }}' '${{ parameters.token }}'
    name: build
    displayName: 'Queue App Center Build'
  - publish: ${{ variables.build_output }}
    artifact: ${{ parameters.artifact_name }}
    displayName: 'Upload APK to Azure Pipelines'