parameters:
- name: owner
  type: string
- name: app
  type: string
- name: branch
  type: string
- name: artifact-name
  type: string
- name: token
  type: string

jobs:
- job: appcenter
  displayName: 'Queue App Center Build'
  pool:
    vmImage: ubunto-latest
  variables:
    build_output: '$(Agent.TempDirectory)/app-center'
  steps:
  - displayName: 'Install App Center CLI and Dependencies'
    script: |
      npm install -g appcenter-cli \
      && apk update \
      && apk add curl \
      && apk add jq \
      && apk add git 
  - displayName: 'Queue App Center Build and Wait for Completion'
    name: build
    script: ./scripts/entrypoint.sh '${{ parameters.owner }}' '${{ parameters.app }}' '${{ parameters.branch }}' '${{ variables.build_output }}' '${{ parameters.token }}'
  - publish: ${{ variables.build_output }}
    name: ${{ parameters.artifact-name }}
    displayName: 'Publish Build Artifacts'