name: App Center

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - run: |
          echo 'Creating branch config...'

      - name: Queue Build and Wait
        run: |          
          chmod +x ./scripts/queue-build-and-wait.sh
          ./scripts/queue-build-and-wait.sh ${{ secrets.APP_CENTER_ORG }}/${{ secrets.APP_CENTER_APP }} new-branch ${{ secrets.APP_CENTER_TOKEN }}
  # test:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  # distribute:
  #   runs-on: ubuntu-latest
  #   needs: [test]