on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Creating branch config...'
      - run: |
          chmod +x ..\scripts\queue-build-and-wait.sh
          ..\scripts\queue-build-and-wait.sh ${{ secrets.APP_CENTER_ORG }}/${{ secrets.APP_CENTER_APP }} new-branch ${{ secrets.APP_CENTER_TOKEN }}
  # test:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  # distribute:
  #   runs-on: ubuntu-latest
  #   needs: [test]