name: App Center

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      buildId: ${{ steps.queue-build-and-wait.outputs.buildId }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
          
      - run: |
          echo 'Creating branch config...'

      - name: Queue Build and Wait
        id: queue-build-and-wait
        uses: ./.github/actions/queue-build-and-wait/
        with:
          owner: ${{ secrets.APP_CENTER_ORG }}
          app: ${{ secrets.APP_CENTER_APP }}
          branch: new-branch
          output: build
          token: ${{ secrets.APP_CENTER_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: my-app-apk
          path: build
  # test:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  # distribute:
  #   runs-on: ubuntu-latest
  #   needs: [test]